---
# This file tells https://pre-commit.com/ which hooks are provided by this repo
# for use by other git repos.

- id: helm-pluto-chart-check
  name: helm pluto chart check
  description: Find Kubernetes resources that have been deprecated
  entry: hooks/helm-pluto.py
  language: script
  require_serial: true
  pass_filenames: false
  args: ["--charts", "charts"]
- id: kubectl-score-chart-check
  name: kubectl-score chart check
  description: Kubernetes object analysis with recommendations for improved reliability and security
  entry: hooks/kube-score.py
  language: script
  require_serial: true
  pass_filenames: false
  args: ["--charts", "charts"]
- id: promtool-check-rules
  name: promtool check rules
  description: Validate Prometheus rules files with promtool
  entry: hooks/promtool.py
  language: script
  require_serial: true
  types: [yaml]
  args: ["--type", "rules"]
- id: promtool-check-config
  name: promtool check config
  description: Validate Prometheus configuration files with promtool
  entry: hooks/promtool.py
  language: script
  require_serial: true
  pass_filenames: true
  args: ["--type", "config"]
